### ISSUE TITLE
Looks great, but how do you actually use/install it?

### ISSUE THREAD

**Issue by KaijuKoder** [AlfishSoftware/godot-files-vscode#1]
I installed the latest version of VS  Code godot-tools, but all its gdshader highlighter does is highlight the "shader_type spatial;" line... and nothing else. Unsurprising, since its gdshader.tmLanguage.json file is this:

```
{
    "version": "v0.1.0",
    "scopeName": "source.gdshader",
    "uuid": "3a95d25d-688b-481f-a581-eee47f00e5ca",
    "patterns": [
        {
            "include": "#shader_type"
        },
        {
            "include": "source.glsl"
        }
    ],
    "repository": {
        "shader_type": {
            "match": "(shader_type)",
            "name": "storage.type.glsl"
        }
    }
}
```

Found your package which promises to highlight more, but, don't know how to install it. Advice would be appreciated.

**Comment by AlfishSoftware** [comment]
You just install it alongside godot-tools. Installation instructions are in [releases](https://github.com/AlfishSoftware/godot-files-vscode/releases).
It's not currently available in VS Marketplace, so for VSCode you have to manually download and install it.
If you use VSCodium, it can be installed as normal from the extensions panel.

**Comment by KaijuKoder** [comment]
Fastest response in Github history! Thanks, Alfish! That worked! (and thanks for pointing me at VSCodium)

**Comment by AlfishSoftware** [comment]
@KaijuKoder By the way, note that installing it manually won't give you automatic updates. So in this case, it's highly recommended that you follow this repo by clicking **Watch > Custom > Releases** to get notified on new releases.

**Comment by AlfishSoftware** [comment]
The extension is now available at [VS Marketplace](https://marketplace.visualstudio.com/items?itemName=alfish.godot-files) too, so it can now be installed directly from VSCode as well (including https://vscode.dev and https://github.dev), with auto-updates. :rocket:
