### ISSUE TITLE
Custom syntax coloring / Use same colors in VSCode and Godot

### ISSUE THREAD

**Issue by LaraSQP** [AlfishSoftware/godot-files-vscode#2]
Thank you for developing this extension and making it available to all.

I have installed both `Godot Files` and `godot-tools` but the result regarding syntax highlighting is awful.

This is what a simple script looks in the Godot editor:

![image](https://github.com/AlfishSoftware/godot-files-vscode/assets/12540983/15261fa8-510c-46fb-946d-2712c616d7a3)

And this is what the same script looks like in VSCode:

![image](https://github.com/AlfishSoftware/godot-files-vscode/assets/12540983/8f7b01af-43c1-41db-882c-998b211a99cf)

I would be happy if the syntax coloring in VSCode were identical to Godot's. I just want to use VSCode.

Is there a configuration file where you can choose which colors to use with what?

Thanks again.

**Comment by AlfishSoftware** [comment]
## Why you get different colors from the screenshots

This extension parses the files, providing the syntax coloring "definitions" in the most specific way possible to allow good semantic coloring by theme providers.
The ***specific colors assigned to these definitions are provided by the themes*** in VSCode.
This extension itself doesn't include a theme.

## How to customize syntax coloring

You can change themes using VSCode's :gear: gear button.
You can also install new themes using extensions, which I recommend (built-in VSCode themes are not very advanced).

For example, if you want VSCode to look like Godot, you can [search "godot theme" in the marketplace](https://marketplace.visualstudio.com/search?term=godot%20theme&target=VSCode&category=All%20categories&sortBy=Relevance) (or in the extensions search) and see if you can find one that works well for you.
It's also possible to do the opposite (making a theme in Godot that looks like VSCode).

You can also learn more about VSCode themes [in their docs](https://code.visualstudio.com/docs/getstarted/themes) if you like advanced stuff, such as making your own color overrides.

## How to get the same colors as in the screenshots

***If you like the theme on the [screenshots](https://github.com/AlfishSoftware/godot-files-vscode#readme), it's currently [available only here as a supporter bonus](https://alfish.itch.io/godot-files-vscode).
It includes a corresponding theme for Godot, so you can have a consistent experience on both IDEs***.

The theme is called ***[Semanticolors Dark](https://gist.github.com/AlfishSoftware/32c7f297615004cefdc156e5fb212746)***, as there is a logic for every color. The VSCode theme is very high-quality, and was designed specially for Godot and C#, but should be fairly compatible with most languages.

**Comment by LaraSQP** [comment]
Thank you very, very much for the quick and detailed reply.

Good karma to you.
